import axios from 'axios';

// Function to get runtime config with fallbacks
const getConfig = () => {
  // Production: window.APP_CONFIG (generated by entrypoint)
  // Development: import.meta.env (Vite)
  return {
    apiUrl: window.APP_CONFIG?.API_URL || import.meta.env.VITE_API_URL || 'http://localhost:8000',
    env: window.APP_CONFIG?.ENV || import.meta.env.VITE_ENV || 'development',
  };
};

const config = getConfig();

const api = axios.create({
  baseURL: config.apiUrl,
});

// Request interceptor for debugging
api.interceptors.request.use(
  (request) => {
    console.log(`[${config.env}] API Request:`, request.method.toUpperCase(), request.url);
    return request;
  },
  (error) => Promise.reject(error)
);

// Response interceptor to handle errors
api.interceptors.response.use(
  (response) => response,
  (error) => {
    console.error('API Error:', error);
    return Promise.reject(error);
  }
);

export default api;
export { config };
